name: Deploy ANFC App

on:
  push:
    branches:
      - main            # run on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy over SSH
        env:
          SSH_PASS: ${{ secrets.PRODUCTION_SSH_PASSWORD }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
        run: |
          sshpass -p "$SSH_PASS" \
            ssh -T -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" <<EOF
              set -euo pipefail

              cd app.alfaandfriends.com
              git pull origin main
              npm install
              npm run build
              composer install --no-interaction --prefer-dist --optimize-autoloader
              php artisan optimize:clear
          EOF
